apiVersion: apps/v1
kind: Deployment
metadata:
  name: linebot-k8s-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linebot-k8s-go
  template:
    metadata:
      labels:
        app: linebot-k8s-go
    spec:
      containers:
      - name: linebot-k8s-go
        image: asia-northeast1-docker.pkg.dev/img2pdf-linebot-k8s-go/docker-repository/linebot-k8s-go:v1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: linebot-k8s-go-service
spec:
  selector:
    app: linebot-k8s-go
